name: gce
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.10.8
  - libcxx=12.0.1
  - libffi=3.4.2
  - libzlib=1.2.11
  - ncurses=6.2
  - openssl=3.0.0
  - pip=21.3.1
  - python=3.9.7
  - python_abi=3.9
  - readline=8.1
  - setuptools=58.5.3
  - sqlite=3.36.0
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - appnope==0.1.2
    - asttokens==2.0.5
    - backcall==0.2.0
    - cycler==0.11.0
    - decorator==5.1.0
    - executing==0.8.2
    - ipython==7.30.1
    - jedi==0.18.1
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - numpy==1.21.4
    - pandas==1.3.4
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - prompt-toolkit==3.0.24
    - ptyprocess==0.7.0
    - pure-eval==0.2.1
    - pygments==2.10.0
    - pyparsing==3.0.4
    - python-dateutil==2.8.2
    - pytz==2021.3
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - six==1.16.0
    - threadpoolctl==3.0.0
    - traitlets==5.1.1
    - varname==0.8.1
    - wcwidth==0.2.5
