name: gce
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.10.8
  - libcxx=12.0.1
  - libffi=3.4.2
  - libzlib=1.2.11
  - ncurses=6.2
  - openssl=3.0.0
  - pip=21.3.1
  - python=3.9.7
  - python_abi=3.9
  - readline=8.1
  - setuptools=58.5.3
  - sqlite=3.36.0
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - alabaster==0.7.12
    - appnope==0.1.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==4.1.0
    - certifi==2021.10.8
    - cffi==1.15.0
    - charset-normalizer==2.0.11
    - colorama==0.4.4
    - cycler==0.11.0
    - debugpy==1.5.1
    - decorator==5.1.0
    - defusedxml==0.7.1
    - dill==0.3.4
    - docutils==0.17.1
    - entrypoints==0.4
    - executing==0.8.2
    - idna==3.3
    - imagesize==1.3.0
    - importlib-metadata==4.10.1
    - ipykernel==6.9.0
    - ipython==7.30.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-client==7.1.2
    - jupyter-console==6.4.0
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - keyring==23.5.0
    - kiwisolver==1.3.2
    - markdown-it-py==2.0.1
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - mdit-py-plugins==0.3.0
    - mdurl==0.1.0
    - mistune==0.8.4
    - myst-parser==0.16.1
    - nbclient==0.5.10
    - nbconvert==6.4.1
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - notebook==6.4.8
    - numpy==1.21.4
    - packaging==21.3
    - pandas==1.3.4
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - pkginfo==1.8.2
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.24
    - ptyprocess==0.7.0
    - pure-eval==0.2.1
    - pycparser==2.21
    - pygments==2.10.0
    - pyparsing==3.0.4
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qtconsole==5.2.2
    - qtpy==2.0.1
    - readme-renderer==32.0
    - requests==2.27.1
    - requests-toolbelt==0.9.1
    - rfc3986==2.0.0
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - send2trash==1.8.0
    - six==1.16.0
    - snowballstemmer==2.2.0
    - sphinx==4.4.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - terminado==0.13.1
    - testpath==0.5.0
    - threadpoolctl==3.0.0
    - tornado==6.1
    - tqdm==4.62.3
    - traitlets==5.1.1
    - twine==3.8.0
    - urllib3==1.26.8
    - varname==0.8.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.2
    - zipp==3.7.0
