name: gce
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.10.8
  - libcxx=12.0.1
  - libffi=3.4.2
  - libzlib=1.2.11
  - ncurses=6.2
  - openssl=3.0.0
  - pip=21.3.1
  - python=3.9.7
  - python_abi=3.9
  - readline=8.1
  - setuptools=58.5.3
  - sqlite=3.36.0
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - alabaster==0.7.12
    - appnope==0.1.2
    - asttokens==2.0.5
    - attrs==21.4.0
    - babel==2.9.1
    - backcall==0.2.0
    - certifi==2021.10.8
    - charset-normalizer==2.0.11
    - cycler==0.11.0
    - decorator==5.1.0
    - docutils==0.17.1
    - executing==0.8.2
    - idna==3.3
    - imagesize==1.3.0
    - importlib-metadata==4.10.1
    - ipython==7.30.1
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - markdown-it-py==2.0.1
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - mdit-py-plugins==0.3.0
    - mdurl==0.1.0
    - myst-parser==0.16.1
    - numpy==1.21.4
    - packaging==21.3
    - pandas==1.3.4
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - prompt-toolkit==3.0.24
    - ptyprocess==0.7.0
    - pure-eval==0.2.1
    - pygments==2.10.0
    - pyparsing==3.0.4
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - requests==2.27.1
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - six==1.16.0
    - snowballstemmer==2.2.0
    - sphinx==4.4.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - threadpoolctl==3.0.0
    - traitlets==5.1.1
    - urllib3==1.26.8
    - varname==0.8.1
    - wcwidth==0.2.5
    - zipp==3.7.0
